### PR TITLE
Adding Smoke Signal to new Events section

### PR DESCRIPTION
**Pull request by ngerakines**

### CODE REVIEW

**Comment by tom-sherman** [comment]
What do you think about naming the section "other atproto apps" and including https://frontpage.fyi/ and https://whtwnd.com/ there?

**Comment by tom-sherman** [comment]
I have a related PR here: https://github.com/beeman/awesome-atproto/pull/13

**Comment by notjuliet** [comment]
I'd rather not add too many categories that otherwise wouldn't fit for anything else existing.
Still, I'll merge it as it is, the category isn't inaccurate, but maybe I'll reorganize it later.
For other atproto apps, they're worth highlighting as long as they have some use to a Bluesky user, and work in relation to it. I thought about making an awesome-atproto list too, since the existing one seems unmaintained, but right now I'd rather just stick to this one list.

**Comment by tom-sherman** [comment]
@notjuliet i'd like to add frontpage and whtwnd, what sections do you recommend adding them to?

**Comment by notjuliet** [comment]
Blogging?
Though frontpage seems to be more like a link aggregator.
I was originally trying to avoid having an "other" category and keep them specific enough, but we might just go with that if it becomes too unwieldy.

**Comment by tom-sherman** [comment]
Yeah that's why I was suggesting to put all of these under a heading like "non-Bluesky atproto apps". Happy to do other though 👍

**Pull request merged**
